/*
Xero Accounting API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.40.0
Contact: api@xero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ReportAttribute type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReportAttribute{}

// ReportAttribute struct for ReportAttribute
type ReportAttribute struct {
	Id *string `json:"Id,omitempty"`
	Value *string `json:"Value,omitempty"`
}

// NewReportAttribute instantiates a new ReportAttribute object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReportAttribute() *ReportAttribute {
	this := ReportAttribute{}
	return &this
}

// NewReportAttributeWithDefaults instantiates a new ReportAttribute object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReportAttributeWithDefaults() *ReportAttribute {
	this := ReportAttribute{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ReportAttribute) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportAttribute) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ReportAttribute) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ReportAttribute) SetId(v string) {
	o.Id = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ReportAttribute) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportAttribute) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ReportAttribute) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *ReportAttribute) SetValue(v string) {
	o.Value = &v
}

func (o ReportAttribute) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReportAttribute) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["Id"] = o.Id
	}
	if !IsNil(o.Value) {
		toSerialize["Value"] = o.Value
	}
	return toSerialize, nil
}

type NullableReportAttribute struct {
	value *ReportAttribute
	isSet bool
}

func (v NullableReportAttribute) Get() *ReportAttribute {
	return v.value
}

func (v *NullableReportAttribute) Set(val *ReportAttribute) {
	v.value = val
	v.isSet = true
}

func (v NullableReportAttribute) IsSet() bool {
	return v.isSet
}

func (v *NullableReportAttribute) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReportAttribute(val *ReportAttribute) *NullableReportAttribute {
	return &NullableReportAttribute{value: val, isSet: true}
}

func (v NullableReportAttribute) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReportAttribute) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


