/*
Xero Accounting API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.40.0
Contact: api@xero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PaymentDelete type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentDelete{}

// PaymentDelete struct for PaymentDelete
type PaymentDelete struct {
	// The status of the payment.
	Status string `json:"Status"`
}

// NewPaymentDelete instantiates a new PaymentDelete object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentDelete(status string) *PaymentDelete {
	this := PaymentDelete{}
	this.Status = status
	return &this
}

// NewPaymentDeleteWithDefaults instantiates a new PaymentDelete object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentDeleteWithDefaults() *PaymentDelete {
	this := PaymentDelete{}
	var status string = "DELETED"
	this.Status = status
	return &this
}

// GetStatus returns the Status field value
func (o *PaymentDelete) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *PaymentDelete) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *PaymentDelete) SetStatus(v string) {
	o.Status = v
}

func (o PaymentDelete) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentDelete) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Status"] = o.Status
	return toSerialize, nil
}

type NullablePaymentDelete struct {
	value *PaymentDelete
	isSet bool
}

func (v NullablePaymentDelete) Get() *PaymentDelete {
	return v.value
}

func (v *NullablePaymentDelete) Set(val *PaymentDelete) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentDelete) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentDelete) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentDelete(val *PaymentDelete) *NullablePaymentDelete {
	return &NullablePaymentDelete{value: val, isSet: true}
}

func (v NullablePaymentDelete) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentDelete) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


